# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCITS5505():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_cITS5505(self):
        self.driver.get("http://127.0.0.1:8080/")
        self.driver.set_window_size(1562, 1296)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "username").send_keys("Admin")
        self.driver.find_element(By.ID, "password").send_keys("123123")
        self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Following").click()
        self.driver.find_element(By.LINK_TEXT, "All Posts").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .card-img-top").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.LINK_TEXT, "3").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-img").click()
        self.driver.find_element(By.LINK_TEXT, "My Channel").click()
        self.driver.find_element(By.LINK_TEXT, "Following").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-img").click()
        self.driver.find_element(By.LINK_TEXT, "My Channel").click()
        self.driver.find_element(By.LINK_TEXT, "Followers").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-img").click()
        self.driver.find_element(By.LINK_TEXT, "My Channel").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .card-img-top").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-img").click()
        self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
        self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
        self.driver.find_element(By.ID, "job_description").click()
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-img").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

