"""Initial migration.

Revision ID: 953e3421aacc
Revises: 
Create Date: 2024-05-08 05:29:18.788710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953e3421aacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
    #默认输入3总category到数据库中
    op.bulk_insert('category', [
        {'id': 1, 'name': 'Interview'},
        {'id': 2, 'name': 'Recruitment'},
        {'id': 3, 'name': 'Job Search'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_column('name')
    op.execute("DELETE FROM category WHERE id IN (1, 2, 3)")
    # ### end Alembic commands ###
